# OHL Prospect Analysis - Data Prep

The purpose of this notebook is to clean data in order to analyze OHL prospects, their statistics, and their probability of succeeding in the NHL. I have data of OHL rosters, OHL stats, and basic NHL stats like points and games played.

In [1]:
#Import packages
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df_roster = pd.read_excel("OHL_roster_data.xlsx")

In [3]:
df_ohl_stats = pd.read_excel("OHL stats data.xlsx")

In [5]:
df_draft = pd.read_excel("C:/Users/BRG4142/Documents/hockey stuff/NHL Draft data/NHL_draft_data.xlsx")

In [6]:
df_roster.head()

,Jersey,Rookie,Player2,Last_Name,First_Name,Player,Pos,Shoots,Height,Height_Ft,Height_In,Height_Inches,Weight,DOB,Hometown,Draft,Year,Team
0,10,NaN,"Dvurechenskii, Vladislav",Dvurechenskii,Vladislav,Vladislav Dvurechenskii,LW,L,6.04,6,4.0,76.0,207,2003-06-18 00:00:00,"Toronto, ON",OHL - BAR (2019) RD: 5 (#90),20-21,Barrie Colts
1,11,NaN,"Cardwell, Ethan",Cardwell,Ethan,Ethan Cardwell,C,R,5.11,5,11.0,71.0,190,2002-08-30 00:00:00,"Courtice, ON",NHL - SJ (2021) RD: 4 (#121),20-21,Barrie Colts
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,OHL - SAG (2018) RD: 2 (#33),20-21,Barrie Colts
3,15,NaN,"Frasca, Jacob",Frasca,Jacob,Jacob Frasca,C,R,6.04,6,4.0,76.0,208,2003-03-19 00:00:00,"Caledon, ON",OHL - BAR (2019) RD: 3 (#45),20-21,Barrie Colts
4,16,NaN,"Tabak, Anthony",Tabak,Anthony,Anthony Tabak,LW,L,6.05,6,5.0,77.0,208,2001-12-06 00:00:00,"Oakville, ON",OHL - SBY (2017) RD: 3 (#53),20-21,Barrie Colts

In [7]:
df_ohl_stats.head()

,Rank,PLAYER,Pos,TEAM,GP,G,A,TP,PPG,PIM,+/-,Year
0,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,37.0,18-19
1,NaN,NaN,NaN,Kingston Frontenacs,24.0,23.0,15.0,38.0,1.58,18.0,1.0,18-19
2,NaN,NaN,NaN,Niagara IceDogs,38.0,25.0,54.0,79.0,2.08,24.0,36.0,18-19
3,2.0,Justin Brazeau,RW,North Bay Battalion,68.0,61.0,52.0,113.0,1.66,40.0,14.0,18-19
4,3.0,Tye Felhaber,W/C,Ottawa 67's,68.0,59.0,50.0,109.0,1.60,45.0,56.0,18-19

# Clean the data

### OHL Rosters

In [8]:
df_roster['DRAFT_NROW'] = df_roster['Draft'].shift(-1)
df_roster['PLAYER_NROW'] = df_roster['Player2'].shift(-1)

In [9]:
def ohl_draft(row):
    if row['PLAYER_NROW'] == None:
        return row['DRAFT_NROW']

In [10]:
df_roster['OHL_DRAFT'] = df_roster.apply(ohl_draft, axis=1)

In [11]:
#drop columns with missing player
df_roster = df_roster.dropna(subset=['Player2'])
df_roster = df_roster[df_roster['Player'] != 'Player']
df_roster = df_roster[df_roster['Player2'] != 'Player']
df_roster = df_roster[df_roster['Last_Name'] != None]

In [12]:
df_roster.head()

,Jersey,Rookie,Player2,Last_Name,First_Name,Player,Pos,Shoots,Height,Height_Ft,...,Height_Inches,Weight,DOB,Hometown,Draft,Year,Team,DRAFT_NROW,PLAYER_NROW,OHL_DRAFT
0,10,NaN,"Dvurechenskii, Vladislav",Dvurechenskii,Vladislav,Vladislav Dvurechenskii,LW,L,6.04,6,...,76.0,207,2003-06-18 00:00:00,"Toronto, ON",OHL - BAR (2019) RD: 5 (#90),20-21,Barrie Colts,NHL - SJ (2021) RD: 4 (#121),"Cardwell, Ethan",None
1,11,NaN,"Cardwell, Ethan",Cardwell,Ethan,Ethan Cardwell,C,R,5.11,5,...,71.0,190,2002-08-30 00:00:00,"Courtice, ON",NHL - SJ (2021) RD: 4 (#121),20-21,Barrie Colts,OHL - SAG (2018) RD: 2 (#33),NaN,None
3,15,NaN,"Frasca, Jacob",Frasca,Jacob,Jacob Frasca,C,R,6.04,6,...,76.0,208,2003-03-19 00:00:00,"Caledon, ON",OHL - BAR (2019) RD: 3 (#45),20-21,Barrie Colts,OHL - SBY (2017) RD: 3 (#53),"Tabak, Anthony",None
4,16,NaN,"Tabak, Anthony",Tabak,Anthony,Anthony Tabak,LW,L,6.05,6,...,77.0,208,2001-12-06 00:00:00,"Oakville, ON",OHL - SBY (2017) RD: 3 (#53),20-21,Barrie Colts,OHL - BAR (2020) RD: 1 (#9),"Haight, Hunter",None
5,19,*,"Haight, Hunter",Haight,Hunter,Hunter Haight,C,R,5.1,5,...,61.0,167,2004-04-04 00:00:00,"Strathroy, ON",OHL - BAR (2020) RD: 1 (#9),20-21,Barrie Colts,NHL - COL (2021) RD: 1 (#28),"Olausson, Oskar",None

In [13]:
df_roster.shape

(4230, 21)

In [14]:
df_roster.dtypes

Jersey            object
Rookie            object
Player2           object
Last_Name         object
First_Name        object
Player            object
Pos               object
Shoots            object
Height            object
Height_Ft         object
Height_In        float64
Height_Inches    float64
Weight            object
DOB               object
Hometown          object
Draft             object
Year              object
Team              object
DRAFT_NROW        object
PLAYER_NROW       object
OHL_DRAFT         object
dtype: object

### OHL Stats

In [15]:
df_ohl_stats['TEAM_NROW'] = df_ohl_stats['TEAM'].shift(-1)

In [16]:
def traded_team(row):
    if row['TEAM'] == 'totals':
        return row['TEAM_NROW']
    else:
        return row['TEAM']

In [17]:
df_ohl_stats['TEAM2'] = df_ohl_stats.apply(traded_team, axis=1)

In [18]:
#drop rows with extra traded stuff
df_ohl_stats = df_ohl_stats.dropna(subset=['PLAYER'])

In [19]:
df_ohl_stats['G_PG'] = df_ohl_stats['G'] / df_ohl_stats['GP']
df_ohl_stats['A_PG'] = df_ohl_stats['A'] / df_ohl_stats['GP']

In [20]:
df_ohl_stats.head()

,Rank,PLAYER,Pos,TEAM,GP,G,A,TP,PPG,PIM,+/-,Year,TEAM_NROW,TEAM2,G_PG,A_PG
0,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,37.0,18-19,Kingston Frontenacs,Kingston Frontenacs,0.774194,1.112903
3,2.0,Justin Brazeau,RW,North Bay Battalion,68.0,61.0,52.0,113.0,1.66,40.0,14.0,18-19,Ottawa 67's,North Bay Battalion,0.897059,0.764706
4,3.0,Tye Felhaber,W/C,Ottawa 67's,68.0,59.0,50.0,109.0,1.60,45.0,56.0,18-19,Soo Greyhounds,Ottawa 67's,0.867647,0.735294
5,4.0,Morgan Frost,C,Soo Greyhounds,58.0,37.0,72.0,109.0,1.88,45.0,33.0,18-19,totals,Soo Greyhounds,0.637931,1.241379
6,5.0,Kevin Hancock,LW/C,totals,70.0,52.0,55.0,107.0,1.53,38.0,18.0,18-19,Owen Sound Attack,Owen Sound Attack,0.742857,0.785714

In [21]:
df_ohl_stats.shape

(2400, 16)

In [22]:
df_ohl_stats.dtypes

Rank         float64
PLAYER        object
Pos           object
TEAM          object
GP           float64
G            float64
A            float64
TP           float64
PPG          float64
PIM          float64
+/-          float64
Year          object
TEAM_NROW     object
TEAM2         object
G_PG         float64
A_PG         float64
dtype: object

In [23]:
for guy in df_ohl_stats['PLAYER'][0:5]:
    print(guy)
    print(len(guy))

Jason Robertson
15
Justin Brazeau
14
Tye Felhaber
12
Morgan Frost
12
Kevin Hancock
13

### NHL Draft

In [24]:
df_draft.head()

,Round,Pick,Draft_Year,Draft_Team,Player,Pos,Drafted_From,Team,League,League2,NHL_GP,NHL_G,NHL_A,NHL_PTS,NHL_PIM,Last_Season
0,1,1,2021,Buffalo,Owen Power,D,U. of Michigan [Big-10],U. of Michigan,Big-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,2021,Seattle,Matty Beniers,C,U. of Michigan [Big-10],U. of Michigan,Big-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,2021,Anaheim,Mason McTavish,C,Peterborough Petes [OHL],Peterborough Petes,OHL,NaN,9,2,1,3,2,2021-22
3,1,4,2021,New Jersey,Luke Hughes,D,U.S. National Under-18 Team [USHL],U.S. National Under-18 Team,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,2021,Columbus,Kent Johnson,C,U. of Michigan [Big-10],U. of Michigan,Big-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
def draft_lg(row):
    if row['League'] == None:
        return row['League2']
    else:
        return row['League']

In [26]:
df_draft['LEAGUE'] = df_draft.apply(draft_lg, axis=1)

In [27]:
#drop columns with missing player
df_draft = df_draft.dropna(subset=['Player'])
df_draft = df_draft[df_draft['Player'] != 'Player']

In [28]:
df_draft['NHL_GPG'] = df_draft['NHL_G']/df_draft['NHL_GP']

In [29]:
df_draft['NHL_APG'] = df_draft['NHL_A']/df_draft['NHL_GP']

In [30]:
df_draft['NHL_PPG'] = df_draft['NHL_PTS']/df_draft['NHL_GP']

In [31]:
#df_draft['REACH_NHL'] = df_draft['NHL_GP'].apply(lambda x: 1 if x > 0 else 0)

In [32]:
#df_draft['NHL_REGULAR'] = df_draft['NHL_GP'].apply(lambda x: 1 if x > 175 else 0)

In [33]:
#create cat for good players
def top_line_player(row):
    if ((row['NHL_REGULAR'] == 1) & (row['NHL_PPG'] > 0.35) & (row['Pos'] == 'D')):
        return 1
    elif ((row['NHL_REGULAR'] == 1) & (row['NHL_PPG'] > 0.65) & ((row['Pos'] == 'F') | (row['Pos'] == 'W') | (row['Pos'] == 'C') | (row['Pos'] == 'L') | (row['Pos'] == 'R'))):
        return 1
    else:
        return 0

In [34]:
#df_draft['TOP_LINE_PLAYER'] = df_draft.apply(top_line_player, axis=1)

In [35]:
df_draft.head(100)[55:70]

,Round,Pick,Draft_Year,Draft_Team,Player,Pos,Drafted_From,Team,League,League2,NHL_GP,NHL_G,NHL_A,NHL_PTS,NHL_PIM,Last_Season,LEAGUE,NHL_GPG,NHL_APG,NHL_PPG
55,2,57,2021,Toronto,Matthew Knies,L,Tri-City Storm [USHL],Tri-City Storm,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHL,NaN,NaN,NaN
56,2,58,2021,Pittsburgh,Tristan Broz,C,Fargo Force [USHL],Fargo Force,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHL,NaN,NaN,NaN
57,2,59,2021,Los Angeles,Samuel Helenius,C,JyP HT Jyvaskyla [SM-liiga],JyP HT Jyvaskyla,SM-liiga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SM-liiga,NaN,NaN,NaN
58,2,60,2021,Arizona,Janis Moser,D,Biel HC [Swiss-A],Biel HC,Swiss-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Swiss-A,NaN,NaN,NaN
59,2,61,2021,Colorado,Sean Behrens,D,U.S. National Under-18 Team [USHL],U.S. National Under-18 Team,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHL,NaN,NaN,NaN
60,2,62,2021,Chicago,Colton Dach,C,Saskatoon Blades [WHL],Saskatoon Blades,WHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WHL,NaN,NaN,NaN
61,2,63,2021,Montreal,Riley Kidney,C,Acadie-Bathurst Titan [QMJHL],Acadie-Bathurst Titan,QMJHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QMJHL,NaN,NaN,NaN
62,2,64,2021,Montreal,Oliver Kapanen,C,Kalpa [Finland Jr.],Kalpa,Finland Jr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland Jr.,NaN,NaN,NaN
66,3,65,2021,NY Rangers,Jayden Grubbe,C,Red Deer Rebels [WHL],Red Deer Rebels,WHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WHL,NaN,NaN,NaN
67,3,66,2021,Anaheim,Sasha Pastujov,R,U.S. National Under-18 Team [USHL],U.S. National Under-18 Team,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHL,NaN,NaN,NaN
68,3,67,2021,Seattle,Ryan Winterton,C,Hamilton Bulldogs [OHL],Hamilton Bulldogs,OHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OHL,NaN,NaN,NaN
69,3,68,2021,New Jersey,Samu Salminen,C,Jokerit [Finland Jr.],Jokerit,Finland Jr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland Jr.,NaN,NaN,NaN
70,3,69,2021,Columbus,Stanislav Svozil,D,Brno Kometa [Czech],Brno Kometa,Czech,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Czech,NaN,NaN,NaN
71,3,70,2021,Detroit,Carter Mazur,L,Tri-City Storm [USHL],Tri-City Storm,USHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHL,NaN,NaN,NaN
72,3,71,2021,St. Louis,Simon Robertsson,R,Skelleftea AIK [SweHL],Skelleftea AIK,SweHL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SweHL,NaN,NaN,NaN

In [36]:
df_draft.shape

(2564, 20)

In [37]:
#df_draft['TOP_LINE_PLAYER'].value_counts()

# Join Data

In [38]:
#OHL stats and roster join
#df_join1 = df_ohl_stats.join(df_roster, lsuffix='PLAYER', rsuffix='Player')
#df_join1 = df_ohl_stats.merge(df_roster, left_on=['PLAYER','Year'], right_on=['Player','Year'])
df_join1 = pd.merge(df_ohl_stats, df_roster,  how='inner', left_on=['PLAYER','Year'], right_on = ['Player','Year'])

In [39]:
df_join1.head()

,Rank,PLAYER,Pos_x,TEAM,GP,G,A,TP,PPG,PIM,...,Height_In,Height_Inches,Weight,DOB,Hometown,Draft,Team,DRAFT_NROW,PLAYER_NROW,OHL_DRAFT
0,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,...,2.0,NaN,200,1999-07-22 00:00:00,"Northville, MI",NHL - DAL (2017) RD: 2 (#39),Kingston Frontenacs,OHL - KGN (2015) RD: 4 (#62),NaN,None
1,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,...,2.0,NaN,200,1999-07-22 00:00:00,"Northville, MI",NHL - DAL (2017) RD: 2 (#39),Niagra Ice Dogs,OHL - KGN (2015) RD: 4 (#62),NaN,None
2,2.0,Justin Brazeau,RW,North Bay Battalion,68.0,61.0,52.0,113.0,1.66,40.0,...,6.0,NaN,226,1998-02-02 00:00:00,"New Liskeard, ON",OHL - NB (2014) RD: 13 (#254),North Bay Battalion,OHL - OS (2015) RD: 3 (#55),"Struthers, Matthew",None
3,3.0,Tye Felhaber,W/C,Ottawa 67's,68.0,59.0,50.0,109.0,1.60,45.0,...,NaN,NaN,189,1998-08-05 00:00:00,"Pembroke, ON",NHL - DAL FA (2019),Ottawa 67's,OHL - SAG (2014) RD: 1 (#10),NaN,None
4,4.0,Morgan Frost,C,Soo Greyhounds,58.0,37.0,72.0,109.0,1.88,45.0,...,NaN,NaN,185,1999-05-14 00:00:00,"Aurora, ON",NHL - PHI (2017) RD: 1 (#27),Soo Greyhounds,OHL - SSM (2015) RD: 4 (#81),NaN,None

In [40]:
df_join1.shape

(2509, 36)

In [41]:
#join with draft data
df = pd.merge(df_join1, df_draft,  how='left', left_on=['PLAYER'], right_on = ['Player'])

In [42]:
df.head()

,Rank,PLAYER,Pos_x,TEAM,GP,G,A,TP,PPG,PIM,...,NHL_GP,NHL_G,NHL_A,NHL_PTS,NHL_PIM,Last_Season,LEAGUE,NHL_GPG,NHL_APG,NHL_PPG
0,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,...,73,25,41,66,28,2021-22,OHL,0.342466,0.561644,0.90411
1,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,...,73,25,41,66,28,2021-22,OHL,0.342466,0.561644,0.90411
2,2.0,Justin Brazeau,RW,North Bay Battalion,68.0,61.0,52.0,113.0,1.66,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,Tye Felhaber,W/C,Ottawa 67's,68.0,59.0,50.0,109.0,1.60,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Morgan Frost,C,Soo Greyhounds,58.0,37.0,72.0,109.0,1.88,45.0,...,31,3,8,11,8,2021-22,OHL,0.0967742,0.258065,0.354839

In [43]:
df.shape

(2513, 56)

In [44]:
df = df.drop_duplicates(subset=['PLAYER', 'Year'], keep='first')

In [45]:
df.head()

,Rank,PLAYER,Pos_x,TEAM,GP,G,A,TP,PPG,PIM,...,NHL_GP,NHL_G,NHL_A,NHL_PTS,NHL_PIM,Last_Season,LEAGUE,NHL_GPG,NHL_APG,NHL_PPG
0,1.0,Jason Robertson,LW,totals,62.0,48.0,69.0,117.0,1.89,42.0,...,73,25,41,66,28,2021-22,OHL,0.342466,0.561644,0.90411
2,2.0,Justin Brazeau,RW,North Bay Battalion,68.0,61.0,52.0,113.0,1.66,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,Tye Felhaber,W/C,Ottawa 67's,68.0,59.0,50.0,109.0,1.60,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Morgan Frost,C,Soo Greyhounds,58.0,37.0,72.0,109.0,1.88,45.0,...,31,3,8,11,8,2021-22,OHL,0.0967742,0.258065,0.354839
5,5.0,Kevin Hancock,LW/C,totals,70.0,52.0,55.0,107.0,1.53,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df.shape

(2185, 56)

In [47]:
df.columns

Index(['Rank', 'PLAYER', 'Pos_x', 'TEAM', 'GP', 'G', 'A', 'TP', 'PPG', 'PIM',
       '+/-', 'Year', 'TEAM_NROW', 'TEAM2', 'G_PG', 'A_PG', 'Jersey', 'Rookie',
       'Player2', 'Last_Name', 'First_Name', 'Player_x', 'Pos_y', 'Shoots',
       'Height', 'Height_Ft', 'Height_In', 'Height_Inches', 'Weight', 'DOB',
       'Hometown', 'Draft', 'Team_x', 'DRAFT_NROW', 'PLAYER_NROW', 'OHL_DRAFT',
       'Round', 'Pick', 'Draft_Year', 'Draft_Team', 'Player_y', 'Pos',
       'Drafted_From', 'Team_y', 'League', 'League2', 'NHL_GP', 'NHL_G',
       'NHL_A', 'NHL_PTS', 'NHL_PIM', 'Last_Season', 'LEAGUE', 'NHL_GPG',
       'NHL_APG', 'NHL_PPG'],
      dtype='object')

In [48]:
#drop unwanted columns
df = df.drop(['Player2','TEAM_NROW','Height_Ft', 'Height_In','Team_x','PLAYER_NROW', 'League','League2','Rookie','Jersey'], axis=1)

In [49]:
#create a few target features
df['REACH_NHL'] = df['NHL_GP'].apply(lambda x: 1 if x > 0 else 0)

In [50]:
df['NHL_REGULAR'] = df['NHL_GP'].apply(lambda x: 1 if x > 175 else 0)

In [51]:
df['TOP_LINE_PLAYER'] = df.apply(top_line_player, axis=1)

In [52]:
df['REACH_NHL'].value_counts()

0    1914
1     271
Name: REACH_NHL, dtype: int64

# Create standardized features for OHL stats

In [53]:
g_mean_1415 = df.loc[(df['Year'] == '14-15'),'G'].mean()
g_std_1415 = df.loc[(df['Year'] == '14-15'),'G'].std()
a_mean_1415 = df.loc[(df['Year'] == '14-15'),'A'].mean()
a_std_1415 = df.loc[(df['Year'] == '14-15'),'A'].std()
tp_mean_1415 = df.loc[(df['Year'] == '14-15'),'TP'].mean()
tp_std_1415 = df.loc[(df['Year'] == '14-15'),'TP'].std()
ppg_mean_1415 = df.loc[(df['Year'] == '14-15'),'PPG'].mean()
ppg_std_1415 = df.loc[(df['Year'] == '14-15'),'PPG'].std()
gpg_mean_1415 = df.loc[(df['Year'] == '14-15'),'G_PG'].mean()
gpg_std_1415 = df.loc[(df['Year'] == '14-15'),'G_PG'].std()
apg_mean_1415 = df.loc[(df['Year'] == '14-15'),'A_PG'].mean()
apg_std_1415 = df.loc[(df['Year'] == '14-15'),'A_PG'].std()
gp_mean_1415 = df.loc[(df['Year'] == '14-15'),'GP'].mean()
gp_std_1415 = df.loc[(df['Year'] == '14-15'),'GP'].std()

g_mean_1516 = df.loc[(df['Year'] == '15-16'),'G'].mean()
g_std_1516 = df.loc[(df['Year'] == '15-16'),'G'].std()
a_mean_1516 = df.loc[(df['Year'] == '15-16'),'A'].mean()
a_std_1516 = df.loc[(df['Year'] == '15-16'),'A'].std()
tp_mean_1516 = df.loc[(df['Year'] == '15-16'),'TP'].mean()
tp_std_1516 = df.loc[(df['Year'] == '15-16'),'TP'].std()
ppg_mean_1516 = df.loc[(df['Year'] == '15-16'),'PPG'].mean()
ppg_std_1516 = df.loc[(df['Year'] == '15-16'),'PPG'].std()
gpg_mean_1516 = df.loc[(df['Year'] == '15-16'),'G_PG'].mean()
gpg_std_1516 = df.loc[(df['Year'] == '15-16'),'G_PG'].std()
apg_mean_1516 = df.loc[(df['Year'] == '15-16'),'A_PG'].mean()
apg_std_1516 = df.loc[(df['Year'] == '15-16'),'A_PG'].std()
gp_mean_1516 = df.loc[(df['Year'] == '15-16'),'GP'].mean()
gp_std_1516 = df.loc[(df['Year'] == '15-16'),'GP'].std()

g_mean_1617 = df.loc[(df['Year'] == '16-17'),'G'].mean()
g_std_1617 = df.loc[(df['Year'] == '16-17'),'G'].std()
a_mean_1617 = df.loc[(df['Year'] == '16-17'),'A'].mean()
a_std_1617 = df.loc[(df['Year'] == '16-17'),'A'].std()
tp_mean_1617 = df.loc[(df['Year'] == '16-17'),'TP'].mean()
tp_std_1617 = df.loc[(df['Year'] == '16-17'),'TP'].std()
ppg_mean_1617 = df.loc[(df['Year'] == '16-17'),'PPG'].mean()
ppg_std_1617 = df.loc[(df['Year'] == '16-17'),'PPG'].std()
gpg_mean_1617 = df.loc[(df['Year'] == '16-17'),'G_PG'].mean()
gpg_std_1617 = df.loc[(df['Year'] == '16-17'),'G_PG'].std()
apg_mean_1617 = df.loc[(df['Year'] == '16-17'),'A_PG'].mean()
apg_std_1617 = df.loc[(df['Year'] == '16-17'),'A_PG'].std()
gp_mean_1617 = df.loc[(df['Year'] == '16-17'),'GP'].mean()
gp_std_1617 = df.loc[(df['Year'] == '16-17'),'GP'].std()

g_mean_1718 = df.loc[(df['Year'] == '17-18'),'G'].mean()
g_std_1718 = df.loc[(df['Year'] == '17-18'),'G'].std()
a_mean_1718 = df.loc[(df['Year'] == '17-18'),'A'].mean()
a_std_1718 = df.loc[(df['Year'] == '17-18'),'A'].std()
tp_mean_1718 = df.loc[(df['Year'] == '17-18'),'TP'].mean()
tp_std_1718 = df.loc[(df['Year'] == '17-18'),'TP'].std()
ppg_mean_1718 = df.loc[(df['Year'] == '17-18'),'PPG'].mean()
ppg_std_1718 = df.loc[(df['Year'] == '17-18'),'PPG'].std()
gpg_mean_1718 = df.loc[(df['Year'] == '17-18'),'G_PG'].mean()
gpg_std_1718 = df.loc[(df['Year'] == '17-18'),'G_PG'].std()
apg_mean_1718 = df.loc[(df['Year'] == '17-18'),'A_PG'].mean()
apg_std_1718 = df.loc[(df['Year'] == '17-18'),'A_PG'].std()
gp_mean_1718 = df.loc[(df['Year'] == '17-18'),'GP'].mean()
gp_std_1718 = df.loc[(df['Year'] == '17-18'),'GP'].std()

g_mean_1819 = df.loc[(df['Year'] == '18-19'),'G'].mean()
g_std_1819 = df.loc[(df['Year'] == '18-19'),'G'].std()
a_mean_1819 = df.loc[(df['Year'] == '18-19'),'A'].mean()
a_std_1819 = df.loc[(df['Year'] == '18-19'),'A'].std()
tp_mean_1819 = df.loc[(df['Year'] == '18-19'),'TP'].mean()
tp_std_1819 = df.loc[(df['Year'] == '18-19'),'TP'].std()
ppg_mean_1819 = df.loc[(df['Year'] == '18-19'),'PPG'].mean()
ppg_std_1819 = df.loc[(df['Year'] == '18-19'),'PPG'].std()
gpg_mean_1819 = df.loc[(df['Year'] == '18-19'),'G_PG'].mean()
gpg_std_1819 = df.loc[(df['Year'] == '18-19'),'G_PG'].std()
apg_mean_1819 = df.loc[(df['Year'] == '18-19'),'A_PG'].mean()
apg_std_1819 = df.loc[(df['Year'] == '18-19'),'A_PG'].std()
gp_mean_1819 = df.loc[(df['Year'] == '18-19'),'GP'].mean()
gp_std_1819 = df.loc[(df['Year'] == '18-19'),'GP'].std()

g_mean_1920 = df.loc[(df['Year'] == '19-20'),'G'].mean()
g_std_1920 = df.loc[(df['Year'] == '19-20'),'G'].std()
a_mean_1920 = df.loc[(df['Year'] == '19-20'),'A'].mean()
a_std_1920 = df.loc[(df['Year'] == '19-20'),'A'].std()
tp_mean_1920 = df.loc[(df['Year'] == '19-20'),'TP'].mean()
tp_std_1920 = df.loc[(df['Year'] == '19-20'),'TP'].std()
ppg_mean_1920 = df.loc[(df['Year'] == '19-20'),'PPG'].mean()
ppg_std_1920 = df.loc[(df['Year'] == '19-20'),'PPG'].std()
gpg_mean_1920 = df.loc[(df['Year'] == '19-20'),'G_PG'].mean()
gpg_std_1920 = df.loc[(df['Year'] == '19-20'),'G_PG'].std()
apg_mean_1920 = df.loc[(df['Year'] == '19-20'),'A_PG'].mean()
apg_std_1920 = df.loc[(df['Year'] == '19-20'),'A_PG'].std()
gp_mean_1920 = df.loc[(df['Year'] == '19-20'),'GP'].mean()
gp_std_1920 = df.loc[(df['Year'] == '19-20'),'GP'].std()

g_mean_2122 = df.loc[(df['Year'] == '21-22'),'G'].mean()
g_std_2122 = df.loc[(df['Year'] == '21-22'),'G'].std()
a_mean_2122 = df.loc[(df['Year'] == '21-22'),'A'].mean()
a_std_2122 = df.loc[(df['Year'] == '21-22'),'A'].std()
tp_mean_2122 = df.loc[(df['Year'] == '21-22'),'TP'].mean()
tp_std_2122 = df.loc[(df['Year'] == '21-22'),'TP'].std()
ppg_mean_2122 = df.loc[(df['Year'] == '21-22'),'PPG'].mean()
ppg_std_2122 = df.loc[(df['Year'] == '21-22'),'PPG'].std()
gpg_mean_2122 = df.loc[(df['Year'] == '21-22'),'G_PG'].mean()
gpg_std_2122 = df.loc[(df['Year'] == '21-22'),'G_PG'].std()
apg_mean_2122 = df.loc[(df['Year'] == '21-22'),'A_PG'].mean()
apg_std_2122 = df.loc[(df['Year'] == '21-22'),'A_PG'].std()
gp_mean_2122 = df.loc[(df['Year'] == '21-22'),'GP'].mean()
gp_std_2122 = df.loc[(df['Year'] == '21-22'),'GP'].std()

In [54]:
#function to standardize OHL stats
def standard_g(row):
    if row['Year'] == '14-15':
        stand_g = (row['G'] - g_mean_1415) / g_std_1415
    elif row['Year'] == '15-16':
        stand_g = (row['G'] - g_mean_1516) / g_std_1516
    elif row['Year'] == '16-17':
        stand_g = (row['G'] - g_mean_1617) / g_std_1617
    elif row['Year'] == '17-18':
        stand_g = (row['G'] - g_mean_1718) / g_std_1718
    elif row['Year'] == '18-19':
        stand_g = (row['G'] - g_mean_1819) / g_std_1819
    elif row['Year'] == '19-20':
        stand_g = (row['G'] - g_mean_1920) / g_std_1920
    elif row['Year'] == '21-22':
        stand_g = (row['G'] - g_mean_2122) / g_std_2122
    return stand_g

def standard_a(row):
    if row['Year'] == '14-15':
        stand_a = (row['A'] - a_mean_1415) / a_std_1415
    elif row['Year'] == '15-16':
        stand_a = (row['A'] - a_mean_1516) / a_std_1516
    elif row['Year'] == '16-17':
        stand_a = (row['A'] - a_mean_1617) / a_std_1617
    elif row['Year'] == '17-18':
        stand_a = (row['A'] - a_mean_1718) / a_std_1718
    elif row['Year'] == '18-19':
        stand_a = (row['A'] - a_mean_1819) / a_std_1819
    elif row['Year'] == '19-20':
        stand_a = (row['A'] - a_mean_1920) / a_std_1920
    elif row['Year'] == '21-22':
        stand_a = (row['A'] - a_mean_2122) / a_std_2122
    return stand_a

def standard_tp(row):
    if row['Year'] == '14-15':
        stand_tp = (row['TP'] - tp_mean_1415) / tp_std_1415
    elif row['Year'] == '15-16':
        stand_tp = (row['TP'] - tp_mean_1516) / tp_std_1516
    elif row['Year'] == '16-17':
        stand_tp = (row['TP'] - tp_mean_1617) / tp_std_1617
    elif row['Year'] == '17-18':
        stand_tp = (row['TP'] - tp_mean_1718) / tp_std_1718
    elif row['Year'] == '18-19':
        stand_tp = (row['TP'] - tp_mean_1819) / tp_std_1819
    elif row['Year'] == '19-20':
        stand_tp = (row['TP'] - tp_mean_1920) / tp_std_1920
    elif row['Year'] == '21-22':
        stand_tp = (row['TP'] - tp_mean_2122) / tp_std_2122
    return stand_tp

def standard_ppg(row):
    if row['Year'] == '14-15':
        stand_ppg = (row['PPG'] - ppg_mean_1415) / ppg_std_1415
    elif row['Year'] == '15-16':
        stand_ppg = (row['PPG'] - ppg_mean_1516) / ppg_std_1516
    elif row['Year'] == '16-17':
        stand_ppg = (row['PPG'] - ppg_mean_1617) / ppg_std_1617
    elif row['Year'] == '17-18':
        stand_ppg = (row['PPG'] - ppg_mean_1718) / ppg_std_1718
    elif row['Year'] == '18-19':
        stand_ppg = (row['PPG'] - ppg_mean_1819) / ppg_std_1819
    elif row['Year'] == '19-20':
        stand_ppg = (row['PPG'] - ppg_mean_1920) / ppg_std_1920
    elif row['Year'] == '21-22':
        stand_ppg = (row['PPG'] - ppg_mean_2122) / ppg_std_2122
    return stand_ppg

def standard_gpg(row):
    if row['Year'] == '14-15':
        stand_gpg = (row['G_PG'] - gpg_mean_1415) / gpg_std_1415
    elif row['Year'] == '15-16':
        stand_gpg = (row['G_PG'] - gpg_mean_1516) / gpg_std_1516
    elif row['Year'] == '16-17':
        stand_gpg = (row['G_PG'] - gpg_mean_1617) / gpg_std_1617
    elif row['Year'] == '17-18':
        stand_gpg = (row['G_PG'] - gpg_mean_1718) / gpg_std_1718
    elif row['Year'] == '18-19':
        stand_gpg = (row['G_PG'] - gpg_mean_1819) / gpg_std_1819
    elif row['Year'] == '19-20':
        stand_gpg = (row['G_PG'] - gpg_mean_1920) / gpg_std_1920
    elif row['Year'] == '21-22':
        stand_gpg = (row['G_PG'] - gpg_mean_2122) / gpg_std_2122
    return stand_gpg

def standard_apg(row):
    if row['Year'] == '14-15':
        stand_apg = (row['A_PG'] - apg_mean_1415) / apg_std_1415
    elif row['Year'] == '15-16':
        stand_apg = (row['A_PG'] - apg_mean_1516) / apg_std_1516
    elif row['Year'] == '16-17':
        stand_apg = (row['A_PG'] - apg_mean_1617) / apg_std_1617
    elif row['Year'] == '17-18':
        stand_apg = (row['A_PG'] - apg_mean_1718) / apg_std_1718
    elif row['Year'] == '18-19':
        stand_apg = (row['A_PG'] - apg_mean_1819) / apg_std_1819
    elif row['Year'] == '19-20':
        stand_apg = (row['A_PG'] - apg_mean_1920) / apg_std_1920
    elif row['Year'] == '21-22':
        stand_apg = (row['A_PG'] - apg_mean_2122) / apg_std_2122
    return stand_apg

def standard_gp(row):
    if row['Year'] == '14-15':
        stand_gp = (row['GP'] - gp_mean_1415) / gp_std_1415
    elif row['Year'] == '15-16':
        stand_gp = (row['GP'] - gp_mean_1516) / gp_std_1516
    elif row['Year'] == '16-17':
        stand_gp = (row['GP'] - gp_mean_1617) / gp_std_1617
    elif row['Year'] == '17-18':
        stand_gp = (row['GP'] - gp_mean_1718) / gp_std_1718
    elif row['Year'] == '18-19':
        stand_gp = (row['GP'] - gp_mean_1819) / gp_std_1819
    elif row['Year'] == '19-20':
        stand_gp = (row['GP'] - gp_mean_1920) / gp_std_1920
    elif row['Year'] == '21-22':
        stand_gp = (row['GP'] - gp_mean_2122) / gp_std_2122
    return stand_gp

In [56]:
df['G_STANDARD'] = df.apply(standard_g, axis=1)
df['A_STANDARD'] = df.apply(standard_a, axis=1)
df['TP_STANDARD'] = df.apply(standard_tp, axis=1)
df['P_PG_STANDARD'] = df.apply(standard_ppg, axis=1)
df['G_PG_STANDARD'] = df.apply(standard_gpg, axis=1)
df['A_PG_STANDARD'] = df.apply(standard_apg, axis=1)
df['GP_STANDARD'] = df.apply(standard_gp, axis=1)

In [57]:
df.dtypes

Rank               float64
PLAYER              object
Pos_x               object
TEAM                object
GP                 float64
G                  float64
A                  float64
TP                 float64
PPG                float64
PIM                float64
+/-                float64
Year                object
TEAM2               object
G_PG               float64
A_PG               float64
Last_Name           object
First_Name          object
Player_x            object
Pos_y               object
Shoots              object
Height              object
Height_Inches      float64
Weight              object
DOB                 object
Hometown            object
Draft               object
DRAFT_NROW          object
OHL_DRAFT           object
Round               object
Pick                object
Draft_Year         float64
Draft_Team          object
Player_y            object
Pos                 object
Drafted_From        object
Team_y              object
NHL_GP              object
NHL_G               object
NHL_A               object
NHL_PTS             object
NHL_PIM             object
Last_Season         object
LEAGUE              object
NHL_GPG             object
NHL_APG             object
NHL_PPG             object
REACH_NHL            int64
NHL_REGULAR          int64
TOP_LINE_PLAYER      int64
G_STANDARD         float64
A_STANDARD         float64
TP_STANDARD        float64
P_PG_STANDARD      float64
G_PG_STANDARD      float64
A_PG_STANDARD      float64
GP_STANDARD        float64
dtype: object

# Create age adjusted stats

In [74]:
#function for season to date
def season_year(row):
    if row['Year'] == '14-15':
        return "9/10/2014"
    elif row['Year'] == '15-16':
        return "9/10/2015"
    elif row['Year'] == '16-17':
        return "9/10/2016"
    elif row['Year'] == '17-18':
        return "9/10/2017"
    elif row['Year'] == '18-19':
        return "9/10/2018"
    elif row['Year'] == '19-20':
        return "9/10/2019"

df['YEAR'] = df.apply(season_year, axis=1)

In [75]:
df['YEAR'].value_counts()

9/10/2014    370
9/10/2019    368
9/10/2017    363
9/10/2016    363
9/10/2018    361
9/10/2015    360
Name: YEAR, dtype: int64

In [76]:
#convert date columns to date formats
from dateutil.relativedelta import relativedelta
df['YEAR'] =  pd.to_datetime(df['YEAR'], infer_datetime_format=True)
df['DOB'] =  pd.to_datetime(df['DOB'], infer_datetime_format=True)

In [77]:
df['SEASON_AGE'] = (df['YEAR'] -df['DOB'])
#df['SEASON_AGE'] = relativedelta(df['YEAR'], df['DOB']).years
#difference_in_years = relativedelta(end_date, start_date).years

In [84]:
df['SEASON_AGE2'] = df['SEASON_AGE'].astype(str)

In [88]:
seas_list = []
for i in df['SEASON_AGE2']:
    #print(i)
    i = i.split(" ")
    #print(i[0])
    seas_list.append(int(i[0]))
    
df['SEASON_AGE2'] = np.array(seas_list)

AttributeError: 'int' object has no attribute 'split'

In [89]:
df['SEASON_AGE2'] = df['SEASON_AGE2'] / 365.25

In [96]:
def season_age(row):
    if row['SEASON_AGE2'] < 16:
        return 'D-2'
    elif row['SEASON_AGE2'] < 17:
        return 'D-1'
    elif row['SEASON_AGE2'] < 18:
        return 'D0'
    elif row['SEASON_AGE2'] < 19:
        return 'D+1'
    elif row['SEASON_AGE2'] < 20:
        return 'D+2'
    else:
        return 'D+3'
df['DRAFT_AGE'] = df.apply(season_age, axis=1)

In [97]:
df[['PLAYER','YEAR','DOB','SEASON_AGE','SEASON_AGE2','DRAFT_AGE']].head(15)

               PLAYER       YEAR        DOB SEASON_AGE  SEASON_AGE2 DRAFT_AGE
0     Jason Robertson 2018-09-10 1999-07-22  6990 days    19.137577       D+2
2      Justin Brazeau 2018-09-10 1998-02-02  7525 days    20.602327       D+3
3        Tye Felhaber 2018-09-10 1998-08-05  7341 days    20.098563       D+3
4        Morgan Frost 2018-09-10 1999-05-14  7059 days    19.326489       D+2
5       Kevin Hancock 2018-09-10 1998-03-02  7497 days    20.525667       D+3
7      Arthur Kaliyev 2018-09-10 2001-06-26  6285 days    17.207392        D0
8           Ben Jones 2018-09-10 1999-02-26  7136 days    19.537303       D+2
9         Akil Thomas 2018-09-10 2000-01-02  6826 days    18.688569       D+1
10       Nate Schnarr 2018-09-10 1999-02-25  7137 days    19.540041       D+2
11      Greg Meireles 2018-09-10 1999-01-01  7192 days    19.690623       D+2
12        Nick Suzuki 2018-09-10 1999-08-10  6971 days    19.085558       D+2
14    Brandon Saigeon 2018-09-10 1998-06-14  7393 days    20.240931       D+3
16     Austen Keating 2018-09-10 1999-03-07  7127 days    19.512663       D+2
17  Anthony Salinitri 2018-09-10 1998-03-05  7494 days    20.517454       D+3
19    Joseph Garreffa 2018-09-10 1999-08-09  6972 days    19.088296       D+2

### Draft year stats

In [105]:
df.groupby('DRAFT_AGE')['P_PG_STANDARD'].describe().sort_values('mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
DRAFT_AGE,,,,,,,,
D+3,236.0,0.420131,0.910383,-1.131149,-0.216212,0.336701,0.902383,3.208773
D+2,502.0,0.294324,1.065957,-1.236603,-0.557108,0.081630,0.943722,4.518639
D+1,577.0,0.103396,1.042729,-1.262411,-0.705342,-0.155698,0.601067,4.186713
D0,546.0,-0.229730,0.924408,-1.289330,-0.902813,-0.506752,0.160664,5.082699
D-1,292.0,-0.551505,0.564856,-1.210240,-0.958134,-0.732587,-0.285675,2.514573
D-2,32.0,-0.627777,0.525774,-1.180119,-0.960132,-0.809096,-0.427455,1.424446

In [102]:
df.groupby('DRAFT_AGE')['PPG'].describe().sort_values('mean', ascending=False)

           count      mean       std   min     25%    50%     75%   max
DRAFT_AGE
D+3        236.0  0.692458  0.347801  0.11  0.4475  0.660  0.8700  1.73
D+2        502.0  0.644761  0.404185  0.08  0.3125  0.550  0.8800  2.14
D+1        577.0  0.570919  0.393868  0.06  0.2800  0.480  0.7600  2.18
D0         546.0  0.445659  0.352401  0.07  0.1900  0.335  0.6150  2.55
D-1        292.0  0.325616  0.214702  0.07  0.1700  0.260  0.4200  1.53
D-2         32.0  0.295000  0.205081  0.07  0.1700  0.250  0.3625  1.14

In [103]:
df.groupby('DRAFT_AGE')['G_PG'].describe().sort_values('mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
DRAFT_AGE,,,,,,,,
D+3,236.0,0.263872,0.191887,0.0,0.099590,0.237229,0.379679,0.897059
D+2,502.0,0.247072,0.195771,0.0,0.081317,0.204504,0.374470,1.000000
D+1,577.0,0.215033,0.181528,0.0,0.073529,0.166667,0.305085,1.031746
D0,546.0,0.168815,0.162653,0.0,0.051393,0.117647,0.231799,0.936170
D-1,292.0,0.126036,0.114504,0.0,0.047619,0.092624,0.169571,0.750000
D-2,32.0,0.118746,0.120243,0.0,0.048490,0.104916,0.155067,0.672414

In [104]:
df.groupby('DRAFT_AGE')['A_PG'].describe().sort_values('mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
DRAFT_AGE,,,,,,,,
D+3,236.0,0.428672,0.199347,0.049180,0.289425,0.397059,0.549265,1.048387
D+2,502.0,0.397779,0.246080,0.000000,0.208955,0.346327,0.533065,1.514286
D+1,577.0,0.355889,0.243107,0.040816,0.179104,0.306452,0.454545,1.350877
D0,546.0,0.276526,0.218041,0.000000,0.123077,0.218182,0.353620,1.617021
D-1,292.0,0.199376,0.130435,0.000000,0.108604,0.164729,0.269841,0.779412
D-2,32.0,0.176190,0.110715,0.048780,0.098420,0.144599,0.211425,0.465517

# Output data to excel

In [99]:
df.to_excel("OHL_Clean.xlsx")